### ISSUE TITLE
ERROR in traverse_grids

### ISSUE THREAD

**Issue by kings-rgb** [nerfstudio-project/nerfacc#244]
when I try to test nerfacc0.5.3 code:

      import torch
      import numpy as np
      import nerfacc
      import os
      os.environ['CUDA_LAUNCH_BLOCKING']='1'
      
      roi_aabb = torch.FloatTensor([-1, -1, -1, 1, 1, 1])
      estimator = nerfacc.OccGridEstimator(roi_aabb=roi_aabb.view(-1), resolution=32, levels=1)
      rays_o = torch.rand(5,3).cuda()
      rays_d = torch.randn(5,3).cuda()
      rays_d = rays_d / rays_d.norm(dim=-1, keepdim=True)
      render_step_size = 0.05
      rr, t1, t2=estimator.sampling(rays_o, rays_d, alpha_fn=None, render_step_size=render_step_size,alpha_thre=0.0,stratified=True,cone_angle=0.0,early_stop_eps=0)
      print(rr.shape)

the error is:

      Traceback (most recent call last):
        File "test.py", line 13, in <module>
          rr, t1, t2=estimator.sampling(rays_o, rays_d, alpha_fn=None, render_step_size=render_step_size,alpha_thre=0.0,stratified=True,cone_angle=0.1,early_stop_eps=0)
        File "/root/anaconda3/envs/py38/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
          return func(*args, **kwargs)
        File "/root/anaconda3/envs/py38/lib/python3.8/site-packages/nerfacc/estimators/occ_grid.py", line 175, in sampling
          t_starts = intervals.vals[intervals.is_left]
      RuntimeError: numel: integer multiplication overflow

And check the output of traverse_grids function, the samples.ray_indices and intervals.vals is empty, so why this error...

**Comment by Chen-Ban** [comment]
> I faced the same problem where all the samples were empty. Quick fix is to add `estimator.binaries[:] = True` right after initializing estimator object.

好方法哈哈哈哈哈哈哈
