### ISSUE TITLE
Thank for your contribution!

### ISSUE THREAD

**Issue by limaolin2017** [nerfstudio-project/nerfacc#283]
I had the following question the first time I ran this:
/miniconda3/envs/mmdet3d-0.17.0/lib/python3.8/site-packages/nerfacc/cuda/csrc/grid.cu:4:10: fatal error: ATen/cuda/CUDAGeneratorImpl.h: No such file or  directory...

**Comment by liruilong940607** [comment]
I see this error `fatal error: ATen/cuda/CUDAGeneratorImpl.h: No such file or directory`. For me this file lives in:

/home/ruilongli/anaconda3/envs/nerfacc/lib/python3.9/site-packages/torch/include/ATen/cuda/CUDAGeneratorImpl.h 

You might want to check if your torch is installed in this conda env correctly.

Alternately, you could install our prebuilt wheels from [here](https://nerfacc-bucket.s3.us-west-2.amazonaws.com/whl/index.html)

**Comment by limaolin2017** [comment]
Hi, does the latest version of nerfacc support torch 1.10?

**Comment by liruilong940607** [comment]
Yes

**Comment by limaolin2017** [comment]
info:'
cuda 113,
Torch 1.10'

When I use the command: 'pip install git+https://github.com/nerfstudio-project/nerfacc.git', I encounter some errors:'Traceback (most recent call last):
  File "/gpfs/home/mli/banmo/scripts/visualize/nvs.py", line 201, in <module>
    app.run(main)
  File "/home/mli/.conda/envs/torch-110/lib/python3.9/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/mli/.conda/envs/torch-110/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/gpfs/home/mli/banmo/scripts/visualize/nvs.py", line 140, in main
    rendered_chunks = render_rays(nerf_models,
  File "/gpfs/home/mli/banmo/nnutils/rendering.py", line 136, in render_rays
    ray_indices, t_starts, t_ends = estimator.sampling(
  File "/home/mli/.conda/envs/torch-110/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/mli/.conda/envs/torch-110/lib/python3.9/site-packages/nerfacc/estimators/occ_grid.py", line 164, in sampling
    intervals, samples, _ = traverse_grids(
  File "/home/mli/.conda/envs/torch-110/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/mli/.conda/envs/torch-110/lib/python3.9/site-packages/nerfacc/grid.py", line 165, in traverse_grids
    intervals, samples, termination_planes = _C.traverse_grids(
  File "/home/mli/.conda/envs/torch-110/lib/python3.9/site-packages/nerfacc/cuda/__init__.py", line 13, in call_cuda
    return getattr(_C, name)(*args, **kwargs)
RuntimeError: CUDA error: an illegal memory access was encountered'

**Comment by liruilong940607** [comment]
Could you dump the input of [this function here ](https://github.com/nerfstudio-project/nerfacc/blob/master/nerfacc/estimators/occ_grid.py#L164-L173)and share it so I can take a look?

**Comment by limaolin2017** [comment]
traverse_grids inputs: {'rays_o': tensor([[-0.2437, -0.0069,  0.0255],
        [-0.2437, -0.0069,  0.0255],
        [-0.2437, -0.0069,  0.0255],
        ...,
        [-0.2437, -0.0069,  0.0255],
        [-0.2437, -0.0069,  0.0255],
        [-0.2437, -0.0069,  0.0255]], device='cuda:0'), 'rays_d': tensor([[ 0.9839,  0.1560, -0.2869],
        [ 0.9840,  0.1560, -0.2848],
        [ 0.9841,  0.1559, -0.2827],
        ...,
        [ 0.9838,  0.1237, -0.3298],
        [ 0.9839,  0.1236, -0.3277],
        [ 0.9840,  0.1235, -0.3256]], device='cuda:0'), 'binaries': tensor([[[[False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          ...,
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False]],

         [[False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          ...,
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False]],

         [[False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          ...,
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False]],

         ...,

         [[False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          ...,
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False]],

         [[False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          ...,
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False]],

         [[False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          ...,
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False]]]]), 'aabbs': tensor([[0.0000, 0.0000, 0.0000, 0.3000, 0.3000, 0.3000]], device='cuda:0'), 'near_planes': tensor([0.2000, 0.2000, 0.2000,  ..., 0.2000, 0.2000, 0.2000], device='cuda:0'), 'far_planes': tensor([1., 1., 1.,  ..., 1., 1., 1.], device='cuda:0'), 'step_size': 0.001, 'cone_angle': 0.0}

**Comment by liruilong940607** [comment]
I can't use these pasted outputs to examine the code.. Could you save them into a file (say .pth or .npz) and upload it here?

**Comment by limaolin2017** [comment]
Thank you for checking!

[inputs.pth.zip](https://github.com/nerfstudio-project/nerfacc/files/14423244/inputs.pth.zip)

**Comment by limaolin2017** [comment]
I have checked the NaN values, shape, and type of input arguments, and there are no existing issues. Can you provide any suggestions on how to handle it?

**Comment by limaolin2017** [comment]
I have checked the GPU memory usage, it is normal.

**Comment by liruilong940607** [comment]
Hi I will  check this issue after ECCV's ddl tmr!

**Comment by ZitongLan** [comment]
Having the same issue on the sampling function, returns 
  File "/home/ztlan/anaconda3/envs/nerf2/lib/python3.8/site-packages/nerfacc/estimators/occ_grid.py", line 164, in sampling
    intervals, samples, _ = traverse_grids(
  File "/home/ztlan/anaconda3/envs/nerf2/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/ztlan/anaconda3/envs/nerf2/lib/python3.8/site-packages/nerfacc/grid.py", line 165, in traverse_grids
    intervals, samples, termination_planes = _C.traverse_grids(
  File "/home/ztlan/anaconda3/envs/nerf2/lib/python3.8/site-packages/nerfacc/cuda/__init__.py", line 13, in call_cuda
    return getattr(_C, name)(*args, **kwargs)
RuntimeError: CUDA error: an illegal memory access was encountered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Is there any update on the issue? Thanks

**Comment by ZitongLan** [comment]
I have solved the issue. I didn't move my estimator to the GPU, so there is illegal memory access occurred.
